[[constraint]]
  branch = "master"
  name = "github.com/g3n/engine"

[[override]]
  branch = "master"
  name = "github.com/go-gl/gl"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/profile"
  version = "1.2.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[prune]
  go-tests = true
  # XXX: work around for dep not downloaing the full repo for g3n and go-gl
  # unused-packages = false
